from sqlalchemy import Column, String, Text, Enum, DateTime, func, Integer, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from app.core.database import Base

class OutgoingLetter(Base):
    """
    Represents an outgoing letter created and sent by the organization.

    This model manages internal correspondence, decrees, or mandates issued
    by the school/institution to external or internal parties.

    Attributes:
        id (int): The primary key for the letter record.
        number (str): The official reference number generated by the institution.
        letter_date (datetime): The date written on the letter.
        sent_date (datetime): The actual date when the letter was dispatched/sent.
        destination (str): The recipient's name or organization.
        subject (str, optional): The summary or title of the letter's content.
        is_decree (bool): Indicates if the letter is a 'Surat Keputusan' (Decree).
        attachment_path (str, optional): Relative file path to the digital copy of the letter.
        classification_id (int): Foreign key referencing the classification category.
        user_id (int): Foreign key referencing the user who created this record.
        created_at (datetime): Timestamp when the record was created.
        updated_at (datetime): Timestamp when the record was last updated.
    """
    __tablename__ = "outgoing_letter"

    id = Column(Integer, primary_key=True, index=True)
    number = Column(String(50), index=True, nullable=False)
    letter_date = Column(DateTime, index=True, nullable=False)
    sent_date = Column(DateTime, index=True, nullable=False)
    destination = Column(String(100), index=True, nullable=False)
    subject = Column(String(255), nullable=True)
    is_decree = Column(Boolean, default=False, index=True, nullable=False)
    attachment_path = Column(String(255), nullable=True)

    
    classification_id = Column(Integer, ForeignKey("classification.id"), index=True, nullable=False)
    classification = relationship("Classification", backref="outgoing_letters", lazy="joined")

    user_id = Column(Integer, ForeignKey('user.id'), nullable=False, index=True)
    user = relationship("User", backref="outgoing_letters", lazy="joined")

    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=False, server_default=func.now(), onupdate=func.now())

    def to_dict(self):
        """Convert outgoing letter object to dictionary format with decree status.
        
        Serializes the OutgoingLetter instance into a JSON-compatible dictionary
        for API responses. This method resolves foreign key relationships to provide
        readable classification codes and usernames, and includes the decree status flag.
        
        Returns:
            dict: A dictionary containing the following keys:
                - id (int): The unique identifier of the outgoing letter
                - number (str): The official letter reference number
                - destination (str): The recipient organization/person name
                - subject (str or None): The letter's subject or title
                - is_decree (bool): Flag indicating if this is a decree (Surat Keputusan)
                - classification (str or None): The classification code (e.g., '002') if relationship exists
                - input_by (str or None): The username of the user who created this record
        """
        return {
            "id": self.id,
            "mail_number": self.number,
            "letter_date": self.letter_date.isoformat() if self.letter_date else None,
            "sent_date": self.sent_date.isoformat() if self.sent_date else None,
            "destination": self.destination,
            "sender": "Tata Usaha",
            "subject": self.subject,
            "is_decree": self.is_decree,
            "classification_code": self.classification.code if self.classification else None,
            "file_path": self.attachment_path,
            "input_by": self.user.username if self.user else None
        }