from sqlalchemy import Column, String, Text, Enum, DateTime, func, Integer, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from app.core.database import Base

class OutgoingLetter(Base):
    """
    Represents an outgoing letter created and sent by the organization.

    This model manages internal correspondence, decrees, or mandates issued
    by the school/institution to external or internal parties.

    Attributes:
        id (int): The primary key for the letter record.
        number (str): The official reference number generated by the institution.
        letter_date (datetime): The date written on the letter.
        sent_date (datetime): The actual date when the letter was dispatched/sent.
        destination (str): The recipient's name or organization.
        subject (str, optional): The summary or title of the letter's content.
        is_decree (Enum): Indicates if the letter is a 'Surat Keputusan' (Decree).
                          Options: 'yes', 'no'.
        attachment_path (str, optional): Relative file path to the digital copy of the letter.
        classification_id (int): Foreign key referencing the classification category.
        user_id (int): Foreign key referencing the user who created this record.
        created_at (datetime): Timestamp when the record was created.
        updated_at (datetime): Timestamp when the record was last updated.
    """
    __tablename__ = "outgoing_letter"

    id = Column(Integer, primary_key=True, index=True)
    number = Column(String(50), index=True, nullable=False)
    letter_date = Column(DateTime, index=True, nullable=False)
    sent_date = Column(DateTime, index=True, nullable=False)
    destination = Column(String(100), index=True, nullable=False)
    subject = Column(String(255), nullable=True)
    is_decree = Column(Boolean, default=False, index=True, nullable=False)
    attachment_path = Column(String(255), nullable=True)

    
    classification_id = Column(Integer, ForeignKey("classification.id"), index=True, nullable=False)
    classification = relationship("Classification", backref="outgoing_letters")

    user_id = Column(Integer, ForeignKey('user.id'), nullable=False, index=True)
    user = relationship("User", backref="outgoing_letters")

    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=False, server_default=func.now(), onupdate=func.now())

    def to_dict(self):
        """
        Serializes the OutgoingLetter object into a dictionary format.

        Returns:
            dict: A dictionary containing letter details including the decree status,
                  classification code, and the creator's username.
        """
        return {
            "id": self.id,
            "number": self.number,
            "destination": self.destination,
            "subject": self.subject,
            "is_decree": self.is_decree,
            "classification": self.classification.code if self.classification else None,
            "input_by": self.user.username if self.user else None
        }